name: MacOSX BigSur MetaCall build
on: [push]
jobs:
  build-action:
    runs-on: macos-latest
    steps:
      - name: Checkout upstream MetaCall Distributable MacOS 
        uses: actions/checkout@v3
      - run: | 
          chmod +x ./build.sh
          ./build.sh
      - name: Upload build tarball production artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: metacall-tarball
          path: metacall-tarball-macos-x64.zip
          if-no-files-found: error
  python-tests:
    name: Python loader tests
    needs: build-action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-12, macos-10.15]
    steps:
      - name: Download build/artifact from cache
        uses: actions/download-artifact@v3
        with:
          name: metacall-tarball
          path: tarball
      - run: | 
          unzip tarball/metacall-tarball-macos-x64.zip
          echo "print(\"Hello World from Python GitHub Actions\")" > py-eval-test.py
          ./metacall.sh ./py-eval-test.py
